name: Docker Fullstack CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only push images on push, not PR

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./STUDENTAPI-SPRINGBOOT
          file: ./STUDENTAPI-SPRINGBOOT/backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./STUDENTAPI-REACT
          file: ./STUDENTAPI-REACT/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-frontend:latest

  build-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run on PR

    steps:
      - uses: actions/checkout@v4
      
      - name: Test build main Dockerfile
        run: docker build . --file Dockerfile --tag test-image:$(date +%s)
